osukhoroslov/dslab

.gitignore, crates/cloud-plugin/Cargo.toml, crates/cloud-plugin/src/core/config.rs, crates/cloud-plugin/src/extensions/azure_dataset_reader.rs, crates/cloud-plugin/src/extensions/dataset_reader.rs, crates/cloud-plugin/src/extensions/huawei_dataset_reader.rs, crates/cloud-plugin/src/extensions/mod.rs, crates/cloud-plugin/src/extensions/vm_migrator.rs, crates/cloud-plugin/src/simulation.rs, examples/cloud-plugin-traces/Cargo.toml, examples/cloud-plugin-traces/azure.yaml, examples/cloud-plugin-traces/huawei.yaml, examples/cloud-plugin-traces/readme.md, examples/cloud-plugin-traces/src/main.rs
1) Создал общий интерфейс для чтения датасетов и подачи их нагрузки на облако
2) Добавил датасет от Huawei в пример
=> feat cloud plugin: huawei dataset parser

crates/dslab-dag/src/parsers/dot_parser.rs, crates/dslab-dag/src/parsers/mod.rs, crates/dslab-dag/src/runner.rs, examples/dag/src/main.rs, examples/dag/traces/trace_diamond.json, examples/dag/traces/trace_epigenomics.json, examples/dag/traces/trace_map_reduce.json, examples/dag/traces/trace_montage.json, examples/dag/traces/trace_reuse_files.json, tools/dag-draw/src/app_data.rs, tools/dag-draw/src/data.rs, tools/dag-draw/src/timeline_widget.rs
Добавил парсер dot-формата. Сравнил со старым -- montage.dot парсится одинаково.
В прошлом PR почему-то потерялись коммиты про фикс dag-draw, снова исправил здесь
=> Add dot_parser

crates/dslab-core/src/context.rs, crates/dslab-core/src/simulation.rs, crates/dslab-core/src/state.rs, crates/dslab-mp-python/Cargo.toml, crates/dslab-mp-python/python/dslabmp.py, crates/dslab-mp-python/src/lib.rs, crates/dslab-mp/Cargo.toml, crates/dslab-mp/src/context.rs, crates/dslab-mp/src/events.rs, crates/dslab-mp/src/message.rs, crates/dslab-mp/src/network.rs, crates/dslab-mp/src/node.rs, crates/dslab-mp/src/process.rs, crates/dslab-mp/src/system.rs, examples/mp-guarantees/Cargo.toml, examples/mp-guarantees/python/solution.py, examples/mp-guarantees/src/main.rs, examples/mp-ping-pong/Cargo.toml, examples/mp-ping-pong/python/basic.py, examples/mp-ping-pong/python/retry.py, examples/mp-ping-pong/src/basic/client.rs, examples/mp-ping-pong/src/basic/server.rs, examples/mp-ping-pong/src/main.rs, examples/mp-ping-pong/src/retry/client.rs, examples/mp-ping-pong/src/retry/server.rs
=> Port of Python integration and recent developments from dslib

crates/dslab-mp/src/network.rs, crates/dslab-mp/src/system.rs, crates/dslab-mp/src/test.rs, crates/dslab-network/src/topology.rs, crates/dslab-network/src/topology_model.rs, crates/dslab-network/src/topology_resolver.rs, examples/master-workers/src/main.rs, examples/master-workers/src/master.rs, examples/mp-guarantees/src/main.rs, examples/mp-ping-pong/src/main.rs
=> Fixed clippy warnings

crates/dslab-faas/src/coldstart.rs, crates/dslab-faas/src/config.rs, crates/dslab-faas/src/container.rs, crates/dslab-faas/src/cpu.rs, crates/dslab-faas/src/extra/arima_extra.rs, crates/dslab-faas/src/extra/azure_trace.rs, crates/dslab-faas/src/extra/hermes.rs, crates/dslab-faas/src/extra/hybrid_histogram.rs, crates/dslab-faas/src/extra/opendc_trace.rs, crates/dslab-faas/src/extra/resolvers.rs, crates/dslab-faas/src/host.rs, crates/dslab-faas/src/invocation.rs, crates/dslab-faas/src/invoker.rs, crates/dslab-faas/src/parallel.rs, crates/dslab-faas/src/resource.rs, crates/dslab-faas/src/scheduler.rs, crates/dslab-faas/src/simulation.rs, crates/dslab-faas/src/util.rs, examples/faas-opendc-benchmark/src/main.rs, examples/faas-parallel/src/main.rs, examples/faas-scheduling-experiment/src/main.rs, examples/serverless-in-the-wild/src/main.rs
=> [faas] Fixed clippy warnings

examples/faas-opendc-benchmark/Cargo.toml, examples/faas-opendc-benchmark/src/main.rs, examples/faas-parallel/Cargo.toml, examples/faas-parallel/src/main.rs, examples/faas-scheduling-experiment/Cargo.toml, examples/faas-scheduling-experiment/readme.md, examples/faas-scheduling-experiment/src/main.rs, examples/serverless-in-the-wild/Cargo.toml, examples/serverless-in-the-wild/readme.md, examples/serverless-in-the-wild/src/main.rs
=> [faas] Switched all examples to clap

crates/dslab-faas/Cargo.toml, crates/dslab-faas/src/coldstart.rs, crates/dslab-faas/src/container.rs, crates/dslab-faas/src/cpu.rs, crates/dslab-faas/src/extra/azure_trace.rs, crates/dslab-faas/src/extra/hermes.rs, crates/dslab-faas/src/extra/resolvers.rs, crates/dslab-faas/src/host.rs, crates/dslab-faas/src/invoker.rs, crates/dslab-faas/src/lib.rs, crates/dslab-faas/src/parallel.rs, crates/dslab-faas/src/scheduler.rs, crates/dslab-faas/src/simulation.rs, crates/dslab-faas/src/stats.rs, crates/dslab-faas/tests/common/mod.rs, crates/dslab-faas/tests/test_contention.rs, crates/dslab-faas/tests/test_sample_metric.rs, crates/dslab-faas/tests/test_simulation.rs, crates/dslab-faas/tests/test_stats.rs, examples/faas-opendc-benchmark/src/main.rs, examples/faas-parallel/src/main.rs, examples/faas-scheduling-experiment/config.yaml, examples/faas-scheduling-experiment/src/main.rs, examples/faas/src/main.rs, examples/serverless-in-the-wild/src/main.rs
- Добавил вычисление квантилей и дисперсии для SampleMetric
- Добавил тесты для метрик и для симуляции
- Реализовал сбор метрик для каждой функции отдельно
- Поправил очень проблемный баг с очередью инвокера
- Добавил в LeastLoadedScheduler и HermesScheduler возможность использовать суммарное число вызовов вместо нагрузки на CPU и возможность избегать хостов, где вызов попадёт в очередь инвокера
=> [faas] Improved stats + fixed invoker queue

crates/dslab-mp-python/python/dslabmp.py, crates/dslab-mp-python/src/lib.rs, crates/dslab-mp/src/context.rs, crates/dslab-mp/src/node.rs
solves https://github.com/osukhoroslov/dslab/issues/164
Про что думаю - можно либо поменять нейминг `set_timer_detailed`, либо сделать какой-нибудь timer builder паттерн, потому что уж очень хочется уметь задать default false значение на force
=> Allow timer overwrites if specified

crates/dslab-dag/src/data_item.rs, crates/dslab-dag/src/tests.rs
=> Fixed computation of network transfer time

crates/dslab-dag/src/dag.rs, crates/dslab-dag/src/dag_simulation.rs, crates/dslab-dag/src/experiment.rs, crates/dslab-dag/src/parsers/dax_parser.rs, crates/dslab-dag/src/parsers/wfcommons_parser.rs, crates/dslab-dag/src/parsers/yaml_parser.rs, crates/dslab-dag/src/runner.rs, crates/dslab-dag/src/scheduler.rs, crates/dslab-dag/src/schedulers/common.rs, crates/dslab-dag/src/schedulers/dls.rs, crates/dslab-dag/src/schedulers/heft.rs, crates/dslab-dag/src/schedulers/lookahead.rs, crates/dslab-dag/src/schedulers/peft.rs, crates/dslab-dag/src/schedulers/portfolio_scheduler.rs, crates/dslab-dag/src/schedulers/simple_scheduler.rs, crates/dslab-dag/src/schedulers/simple_with_data.rs, crates/dslab-dag/src/trace_log.rs, examples/dag-portfolio/src/main.rs, tools/dag-draw/src/app_data.rs, tools/dag-draw/src/draw_utils.rs, tools/dag-draw/src/graph_widget.rs, tools/dag-draw/src/panels_widget.rs, tools/dag-draw/src/timeline_widget.rs
Поправил `cargo clippy` во всех модулях, относящихся к `dag`. Для удобства разбил на 3 коммита
=> Fix dag clippy

crates/dslab-core/src/simulation.rs, crates/dslab-core/src/state.rs, crates/dslab-iaas/src/simulation.rs, crates/dslab-iaas/tests/test_core.rs
=> [core] Advance time in step_for_duration to expected end time

crates/dslab-network/src/network.rs, crates/dslab-network/src/topology.rs, examples/network-topology-benchmark/src/main.rs, examples/network-topology/src/main.rs
- переименовал некоторые вещи
- изменил порядок аргументов в add_link()
- перенес инициализацию топологии раньше
- добавил учёт баланса пропускной способности (total_downlink = total_uplink) в fat-tree
=> Refactoring and improvements

crates/dslab-network/src/network.rs, crates/dslab-network/src/topology.rs, crates/dslab-network/src/topology_model.rs, examples/network-topology-benchmark/Cargo.toml, examples/network-topology-benchmark/src/main.rs, examples/network-topology-benchmark/src/system.rs, examples/network-topology-benchmark/src/topology.rs, examples/network-topology/src/main.rs
В ветке Романа было два теста -- звезда и звезда второго порядка (звезда, где каждый лист заменен на звезду).
Добавил возможность менять размер теста из командной строки вместо константы + сделал пару косметических изменений
=> Network benchmark

crates/dslab-mp/src/mc/dependency.rs, crates/dslab-mp/src/mc/events.rs, crates/dslab-mp/src/mc/pending_events.rs, crates/dslab-mp/src/mc/strategies/bfs.rs, crates/dslab-mp/src/mc/strategies/dfs.rs, crates/dslab-mp/src/mc/strategy.rs, crates/dslab-mp/src/mc/system.rs
=> handle both directives and events

crates/dslab-dag/src/dag_stats.rs, crates/dslab-dag/src/experiment.rs, crates/dslab-dag/src/lib.rs, crates/dslab-dag/src/run_stats.rs, crates/dslab-dag/src/runner.rs
`eprintln!("{}", serde_json::to_string_pretty(runner.borrow().dag_stats()).unwrap());`
=> [dag] Add dag stats

Cargo.lock, crates/dslab-dag/src/network.rs, crates/dslab-network/Cargo.toml, crates/dslab-network/src/network.rs, crates/dslab-network/src/topology.rs, crates/dslab-network/src/topology_model.rs, crates/dslab-network/src/topology_resolver.rs, crates/dslab-network/src/topology_structures.rs, crates/dslab-network/tests/tests.rs, examples/network-topology-benchmark/src/topology.rs, examples/network-topology/src/main.rs
https://github.com/osukhoroslov/dslab/issues/223
=> [network] Support different link types

crates/dslab-storage/src/disk.rs, crates/dslab-storage/src/scheduler.rs, crates/dslab-storage/src/tests.rs, examples/storage-disk-advanced/src/main.rs
- DiskActivity -> DiskOperation
- Операция хранит свой тип
- Событие о завершении операции содержит её id вместо типа для большей гибкости в будущем
- Метод шедулера изменился на `complete` и возвращает завершившуюся операцию
- Событие о выполнении операции её инициатору отправляет диск
=> Storage disk scheduler (refactoring)

crates/dslab-mp/src/logger.rs, crates/dslab-mp/src/mc/error.rs, crates/dslab-mp/src/mc/mod.rs, crates/dslab-mp/src/mc/model_checker.rs, crates/dslab-mp/src/mc/predicates.rs, crates/dslab-mp/src/mc/strategy.rs, crates/dslab-mp/src/mc/system.rs, examples/mp-guarantees/src/main.rs, examples/mp-ping-pong/python/retry.py, examples/mp-ping-pong/src/main.rs
Для гарантий все работает примерно так же, как и для пинг-понга, так что предлагаю заносить их вместе, чтобы одну и ту же работу не проделывать в двух разных ревью
=> [mp/mc] model checking tests for mp-ping-pong & mp-guarantees

crates/dslab-mp/readme.md, crates/dslab-mp/src/context.rs, crates/dslab-mp/src/events.rs, crates/dslab-mp/src/lib.rs, crates/dslab-mp/src/logger.rs, crates/dslab-mp/src/message.rs, crates/dslab-mp/src/network.rs, crates/dslab-mp/src/node.rs, crates/dslab-mp/src/process.rs, crates/dslab-mp/src/system.rs, crates/dslab-mp/src/test.rs
=> [mp] Add documentation

crates/dslab-faas/src/container.rs, crates/dslab-faas/src/host.rs, crates/dslab-faas/src/invoker.rs
Наконец дошли руки залить эти фиксы)
=> [faas] Small fixes
